---
- name: Update server packages
  yum: 
    name: "*"
    state: latest

- name: create directory for java
  file:
    path: /home/centos/Java_Installer
    state: directory

- name: Download Java package installer
  shell: |
    wget -O /home/centos/Java_Installer/jdk151.rpm --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/8u151-b12/e758a0de34e24606bca991d704f6dcbf/jdk-8u151-linux-x64.rpm"

- name: Install package
  yum:
     name: /home/centos/Java_Installer/jdk151.rpm
     state: present